name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go/**

defaults:
  run:
    working-directory: go

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
          cache-dependency-path: go/go.sum
      - run: go build -o main
      - uses: DataDog/agent-github-action@v1.3.1
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
      - run: ./main
        env:
          DD_ENV: github-actions

  tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
          cache-dependency-path: go/go.sum
      - run: go mod tidy
      - uses: int128/update-generated-files-action@v2

  build:
    uses: int128/docker-build-workflow/.github/workflows/build.yaml@v1
    with:
      context: go
      image: ghcr.io/${{ github.repository }}/go
    permissions:
      contents: read
      packages: write

  test-image:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm 'ghcr.io/${{ github.repository }}/go@${{ needs.build.outputs.digest }}'
